COMMON: &common
  DEBUG: False
  TESTING: False
  THREADED: False
  SECRET_KEY: insecure
  # mongodb数据库配置
  MONGODB_SETTINGS:
    db: "test"
    host: "mongodb://hjw:123456@127.0.0.1:27017" #'127.0.0.1'
    # port: 27017
    # username: 'test'
    # password: '123456'
    # connect: True
    # authentication_source: 'admin'
  MONGODB_DEBUG: False
  # 日志配置文件路径
  LOGGING_CONFIG_PATH: ./config/logging.yaml
  # 日志文件存放位置
  LOGGING_PATH: ./logs

  # 响应信息
  RESPONSE_MESSAGE_CONFIG_PATH: ./config/msg.yaml

  # JSON数据(包括其中的中文)是否显示为ASCII码
  JSON_AS_ASCII: False

DEVELOPMENT: &development
  <<: *common
  DEBUG: True

STAGING: &staging
  <<: *common
  SECRET_KEY: sortasecure

PRODUCTION: &production
  <<: *common
  SECRET_KEY: mdd1##$$%^!DSA#FDSF
